### ISSUE TITLE
how get videos from 2 and more channels?

### ISSUE THREAD

**Issue by rursi** [Shurikn/youtube-xml-discord-bot#2]
how get last videos from 2 and more youtube channels?

**Comment by Shurikn** [comment]
Hi. For now this is only possible if you run two instance of the bot with different config files. But I'll change it so that 1 bot can have multiple youtube channels in the future.

**Comment by Shurikn** [comment]
New version of the config file allow multiple channel to post to, multiple youtube channel to pull from, and also multiple combination of these
